{{- if .Values.ingress.enabled -}}
{{- $fullName := include "camunda-bpm-platform.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version -}}
          {{- range .paths }}
            {{- if kindIs "string" . }}
            - path: {{ . }}
              pathType: ImplementationSpecific
              backend:
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $svcPort }}
            {{- else }}
            - path: {{ .path }}
              pathType: ImplementationSpecific
              backend:
                service:
                  name: {{ .backend.serviceName }}
                  port:
                    {{- if kindIs "string" .backend.servicePort }}
                    name: {{ .backend.servicePort }}
                    {{- else}}
                    number: {{ .backend.servicePort }}
                    {{- end}}
            {{- end }}
          {{- end }}
        {{- else -}}
          {{- range .paths }}
            {{- if kindIs "string" . }}
            - path: {{ . }}
              backend:
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
            {{- else }}
            - path: {{ .path }}
              backend:
                serviceName: {{ .backend.serviceName }}
                servicePort: {{ .backend.servicePort }}
            {{- end }}
          {{- end -}}
        {{- end -}}
    {{- end }}
  {{- end }}
  
